In [1]:
#import the required libraries 
import numpy as np
import matplotlib as plt
import pandas as pd

In [2]:
#read the sonar dataset
dataset = pd.read_csv(r"desktop\sonar.all-data.csv")

In [3]:
print(len(dataset.columns))

61


In [4]:
type(dataset)

pandas.core.frame.DataFrame

In [5]:
dataset

transmitted frequency  angle of incidence  angle of refraction  \
0                   0.0200              0.0371               0.0428   
1                   0.0453              0.0523               0.0843   
2                   0.0262              0.0582               0.1099   
3                   0.0100              0.0171               0.0623   
4                   0.0762              0.0666               0.0481   
5                   0.0286              0.0453               0.0277   
6                   0.0317              0.0956               0.1321   
7                   0.0519              0.0548               0.0842   
8                   0.0223              0.0375               0.0484   
9                   0.0164              0.0173               0.0347   
10                  0.0039              0.0063               0.0152   
11                  0.0123              0.0309               0.0169   
12                  0.0079              0.0086               0.0055   
13                  0.0090              0.0062               0.0253   
14                  0.0124              0.0433               0.0604   
15                  0.0298              0.0615               0.0650   
16                  0.0352              0.0116               0.0191   
17                  0.0192              0.0607               0.0378   
18                  0.0270              0.0092               0.0145   
19                  0.0126              0.0149               0.0641   
20                  0.0473              0.0509               0.0819   
21                  0.0664              0.0575               0.0842   
22                  0.0099              0.0484               0.0299   
23                  0.0115              0.0150               0.0136   
24                  0.0293              0.0644               0.0390   
25                  0.0201              0.0026               0.0138   
26                  0.0151              0.0320               0.0599   
27                  0.0177              0.0300               0.0288   
28                  0.0100              0.0275               0.0190   
29                  0.0189              0.0308               0.0197   
..                     ...                 ...                  ...   
178                 0.0197              0.0394               0.0384   
179                 0.0394              0.0420               0.0446   
180                 0.0310              0.0221               0.0433   
181                 0.0423              0.0321               0.0709   
182                 0.0095              0.0308               0.0539   
183                 0.0096              0.0404               0.0682   
184                 0.0269              0.0383               0.0505   
185                 0.0340              0.0625               0.0381   
186                 0.0209              0.0191               0.0411   
187                 0.0368              0.0279               0.0103   
188                 0.0089              0.0274               0.0248   
189                 0.0158              0.0239               0.0150   
190                 0.0156              0.0210               0.0282   
191                 0.0315              0.0252               0.0167   
192                 0.0056              0.0267               0.0221   
193                 0.0203              0.0121               0.0380   
194                 0.0392              0.0108               0.0267   
195                 0.0129              0.0141               0.0309   
196                 0.0050              0.0017               0.0270   
197                 0.0366              0.0421               0.0504   
198                 0.0238              0.0318               0.0422   
199                 0.0116              0.0744               0.0367   
200                 0.0131              0.0387               0.0329   
201                 0.0335              0.0258               0.0398   
202                 0.0272   

In [6]:
X=dataset.iloc[:,0:60].values

In [7]:
X

array([[0.02  , 0.0371, 0.0428, ..., 0.0084, 0.009 , 0.0032],
       [0.0453, 0.0523, 0.0843, ..., 0.0049, 0.0052, 0.0044],
       [0.0262, 0.0582, 0.1099, ..., 0.0164, 0.0095, 0.0078],
       ...,
       [0.0522, 0.0437, 0.018 , ..., 0.0138, 0.0077, 0.0031],
       [0.0303, 0.0353, 0.049 , ..., 0.0079, 0.0036, 0.0048],
       [0.026 , 0.0363, 0.0136, ..., 0.0036, 0.0061, 0.0115]])

In [8]:
y = dataset.iloc[:,-1].values

In [9]:
y

array(['R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R',
       'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R',
       'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R',
       'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R',
       'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R',
       'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R',
       'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R',
       'R', 'R', 'R', 'R', 'R', 'R', 'M', 'M', 'M', 'M', 'M', 'M', 'M',
       'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M',
       'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M',
       'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M',
       'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M',
       'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M',
       'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M

In [10]:
#encode the dependent variable containing categorical values
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()

In [11]:
encoder.fit(y)

LabelEncoder()

In [12]:
y = encoder.transform(y)

In [13]:
y

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [14]:
#transform the data in training and testing
from sklearn.utils import shuffle
X,y = shuffle(X,y,random_state=1)

In [15]:
from sklearn.model_selection import train_test_split
train_x,test_x,train_y,test_y = train_test_split(X,y,test_size=0.20, random_state=42)

In [16]:
from sklearn.preprocessing import StandardScaler
sc= StandardScaler()
train_x =sc.fit_transform(train_x)
test_x = sc.transform(test_x)

In [17]:
import keras
from keras.models import Sequential
from keras.layers import Dense

Using TensorFlow backend.


In [18]:
keras.__version__

'2.2.4'

In [19]:
model=Sequential()

In [20]:
train_x.shape

(166, 60)

In [21]:
train_y.shape

(166,)

In [22]:
model.add(Dense(input_dim=60,init="random_uniform",activation='relu',output_dim=15))#input layer

C:\Users\PC\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(input_dim=60, activation="relu", units=15, kernel_initializer="random_uniform")`
  """Entry point for launching an IPython kernel.


Instructions for updating:
Colocations handled automatically by placer.


In [23]:
model.add(Dense(output_dim=8,init="random_uniform",activation='relu'))#hidden layer

C:\Users\PC\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=8, kernel_initializer="random_uniform")`
  """Entry point for launching an IPython kernel.


In [24]:
model.add(Dense(output_dim=1,init='random_uniform',activation='sigmoid'))#output layer

C:\Users\PC\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", units=1, kernel_initializer="random_uniform")`
  """Entry point for launching an IPython kernel.


In [25]:
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])#adam=batch gradent descent

In [37]:
#train_y.reshape(1,-1)
train_y.shape

(166,)

In [26]:
model.fit(train_x,train_y,epochs=150, batch_size=83)#epochs no of iteration 

Instructions for updating:
Use tf.cast instead.
Epoch 1/150
166/166 [==============================] - 8s 48ms/step - loss: 0.6932 - acc: 0.4578
Epoch 2/150
166/166 [==============================] - 0s 94us/step - loss: 0.6930 - acc: 0.5361
Epoch 3/150
166/166 [==============================] - 0s 94us/step - loss: 0.6929 - acc: 0.5361
Epoch 4/150
166/166 [==============================] - 0s 94us/step - loss: 0.6927 - acc: 0.5361
Epoch 5/150
166/166 [==============================] - 0s 0us/step - loss: 0.6925 - acc: 0.5361
Epoch 6/150
166/166 [==============================] - 0s 0us/step - loss: 0.6923 - acc: 0.5361
Epoch 7/150
166/166 [==============================] - 0s 0us/step - loss: 0.6921 - acc: 0.5361
Epoch 8/150
166/166 [==============================] - 0s 0us/step - loss: 0.6918 - acc: 0.5361
Epoch 9/150
166/166 [==============================] - 0s 94us/step - loss: 0.6915 - acc: 0.5361
Epoch 10/150
166/166 [==============================] - 0s 188us/step - loss: 0.691

In [28]:
y_pred = model.predict(test_x)

In [29]:
y_pred=(y_pred>0.5)

In [30]:
y_pred

array([[ True],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [ True]])

In [32]:
test_y

array([1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1])

In [34]:
y_p=model.predict(sc.transform(np.array([[0.02,0.0371,0.0428,0.0207,0.0954,0.0986,0.1539,0.1601,0.3109,0.2111,0.1609,0.1582,0.2238,0.0645,0.066,0.2273,0.31,0.2999,0.5078,0.4797,0.5783,0.5071,0.4328,0.555,0.6711,0.6415,0.7104,0.808,0.6791,0.3857,0.1307,0.2604,0.5121,0.7547,0.8537,0.8507,0.6692,0.6097,0.4943,0.2744,0.051,0.2834,0.2825,0.4256,0.2641,0.1386,0.1051,0.1343,0.0383,0.0324,0.0232,0.0027,0.0065,0.0159,0.0072,0.0167,0.018,0.0084,0.009,0.0032
]])))

In [35]:
y_p

array([[0.9249214]], dtype=float32)

In [36]:
y_p=(y_p>0.5)

In [37]:
y_p

array([[ True]])

In [41]:

from sklearn.metrics import accuracy_score
accuracy_score(test_y, y_pred)

0.8809523809523809